server:
  port: 10086
spring:
  application:
    name: ly-registry # 应用名称，会在Eureka中显示
eureka:
  client:
    fetch-registry: false #关闭从Eureka拉取服务
    register-with-eureka: false #关闭把自己注册到Eureka中
    service-url: #Erueka服务网址如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka
  ###################################################
  ######  以下在正式环境内可以不设置   ################
  ### 失效剔除和自我保护---测试阶段设置，正式环境可以不设置
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 1000  # 扫描失效服务的间隔时间（缺省为60*1000ms）